on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Import AWS Secrets From Vault
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: jwt
        role: github-actions-role
        secrets: |
          aws/creds/gha-s3-role access_key | AWS_ACCESS_KEY_ID ;
          aws/creds/gha-s3-role secret_key | AWS_SECRET_ACCESS_KEY

    - name: Checkout Terraform Configuration
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Destroy
      working-directory: ./terraform
      run: terraform destroy -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}

