name: "Terraform Destroy"

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: "Vault Authenticate & Destroy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Fetch from Vault and name this step 'vault'
      - name: Import AWS Secrets From Vault
        id: vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: jwt
          role: github-actions-role              
          secrets: |
            aws/creds/gha-s3-role access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/gha-s3-role secret_key | AWS_SECRET_ACCESS_KEY

      # 2. Bind the Vault outputs explicitly to the Runner Environment
      - name: Export Credentials to Runner Environment
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ steps.vault.outputs.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ steps.vault.outputs.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      # 3. Check if AWS validates them now
      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve